type
  TInteger_4 = 		record const size = 4; end;
	TInteger_8 = 		record const size = 8; end;
	TInteger_16 = 	record const size = 16; end;
	TInteger_24 = 	record const size = 24; end;
	TInteger_32 = 	record const size = 32; end;
	TInteger_48 = 	record const size = 48; end;
	TInteger_64 = 	record const size = 64; end;
	TInteger_96 = 	record const size = 96; end;
	TInteger_128 = 	record const size = 128; end;
	TInteger_256 = 	record const size = 256; end;
	TInteger_512 = 	record const size = 512; end;
	TInteger_1024 = record const size = 1024; end;